# == Schema Information
#
# Table name: questions
#
#  id                :integer          not null, primary key
#  title             :string
#  url               :string
#  incorrect_answers :jsonb
#  answer            :string
#  autogenerated     :boolean          default(FALSE)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  category          :integer          default(0)
#

require 'rails_helper'

RSpec.describe Question, type: :model do
  pending "add some examples to (or delete) #{__FILE__}"
end
