class CreateQuestions < ActiveRecord::Migration[5.1]
  def change
    create_table :questions do |t|
      t.string :title
      t.string :url
      t.jsonb :incorrect_answers
      t.string :answer

      t.boolean :autogenerated, default: false

      t.timestamps
    end
  end
end
