module Fetchers
  class SurgicalTools < Fetcher
    def call
      Question.surgical_tools.delete_all
      photos.each do |photo|
        Question.create!(
          title: nil,
          url: photo[:url],
          answer: photo[:name],
          incorrect_answers: get_three_incorrect_answers(photo[:name]),
          autogenerated: true,
          category: :surgical_tools
        )
      end
    end

    private

    def photos
      @_photos ||= Dir.glob("./public/instrumentar/*").map do |path|
        {
          name: path.gsub("./public/instrumentar/", "").gsub(".jpeg", "").humanize,
          url: path.gsub("./public/", "")
        }
      end
    end

    def get_three_incorrect_answers name
      photos
        .reject{ |photo| photo[:name] == name }
        .sample(3)
        .map{ |photo| photo[:name] }
    end
  end
end
